export default [
  { value: 'yunda', label: '韵达快递' },
  { value: 'yuantong', label: '圆通速递' },
  { value: 'youzhengguonei', label: '邮政快递包裹' },
  { value: 'shentong', label: '申通快递' },
  { value: 'shunfeng', label: '顺丰速运' },
  { value: 'zhongtong', label: '中通快递' },
  { value: 'huitongkuaidi', label: '百世快递' },
  { value: 'jd', label: '京东物流' },
  { value: 'tiantian', label: '天天快递' },
  { value: 'ems', label: 'EMS' },
  { value: 'jtexpress', label: '极兔速递' },
  { value: 'youzhengbk', label: '邮政标准快递' },
  { value: 'zhaijisong', label: '宅急送' },
  { value: 'debangwuliu', label: '德邦' },
  { value: 'debangkuaidi', label: '德邦快递' },
  { value: 'zhongtongkuaiyun', label: '中通快运' },
  { value: 'baishiwuliu', label: '百世快运' },
  { value: 'youshuwuliu', label: '优速快递' },
  { value: 'yundakuaiyun', label: '韵达快运' },
  { value: 'zhongyouex', label: '众邮快递' },
  { value: 'annengwuliu', label: '安能快运' },
  { value: 'yuantongkuaiyun', label: '圆通快运' },
  { value: 'suning', label: '苏宁物流' },
  { value: 'ztky', label: '中铁快运' },
  { value: 'zhongtongguoji', label: '中通国际' },
  { value: 'upsen', label: 'UPS-全球件' },
  { value: 'kuayue', label: '跨越速运' },
  { value: 'youzhengguoji', label: '国际包裹' },
  { value: 'fedex', label: 'FedEx-国际件' },
  { value: 'suer', label: '速尔快递' },
  { value: 'dhlen', label: 'DHL-全球件' },
  { value: 'runhengfeng', label: '全时速运' },
  { value: 'nsf', label: '新顺丰（NSF）' },
  { value: 'annto', label: '安得物流' },
  { value: 'dhl', label: 'DHL-中国件' },
  { value: 'danniao', label: '丹鸟' },
  { value: 'emsguoji', label: 'EMS-国际件' },
  { value: 'lntjs', label: '特急送' },
  { value: 'usps', label: 'USPS' },
  { value: 'yimidida', label: '壹米滴答' },
  { value: 'ewe', label: 'EWE全球快递' },
  { value: 'rrs', label: '日日顺物流' },
  { value: 'lianhaowuliu', label: '联昊通' },
  { value: 'shpost', label: '同城快寄' },
  { value: 'subida', label: '速必达' },
  { value: 'jiuyescm', label: '九曳供应链' },
  { value: 'emsbg', label: 'EMS包裹' },
  { value: 'ups', label: 'UPS' },
  { value: 'disifang', label: '递四方' },
  { value: 'lianbangkuaidi', label: '联邦快递' },
  { value: 'yuanchengwuliu', label: '远成物流' },
  { value: 'xinfengwuliu', label: '信丰物流' },
  { value: 'zhongyouwuliu', label: '中邮物流' },
  { value: 'btexpress', label: '邦泰快运' },
  { value: 'zhuanyunsifang', label: '转运四方' },
  { value: 'sxjdfreight', label: '顺心捷达' },
  { value: 'jinguangsudikuaijian', label: '京广速递' },
  { value: 'auexpress', label: '澳邮中国快运' },
  { value: 'gslhkd', label: '联合快递' },
  { value: 'yuantongguoji', label: '圆通国际' },
  { value: 'kuaijiesudi', label: '快捷速递' },
  { value: 'yuxinwuliu', label: '宇鑫物流' },
  { value: 'tnt', label: 'TNT' },
  { value: 'fujisuyun', label: '富吉速运' },
  { value: 'ubonex', label: '优邦速运' },
  { value: 'longbanwuliu', label: '龙邦速递' },
  { value: 'japanposten', label: '日本（Japan Post）' },
  { value: 'zhimakaimen', label: '芝麻开门' },
  { value: 'meiquick', label: '美快国际物流' },
  { value: 'yuntrack', label: 'YUN TRACK' },
  { value: 'chinaicip', label: '卓志速运' },
  { value: 'dsukuaidi', label: 'D速快递' },
  { value: 'wondersyd', label: '中邮速递' },
  { value: 'guotongkuaidi', label: '国通快递' },
  { value: 'flyway', label: '程光快递' },
  { value: 'auspost', label: '澳大利亚(Australia Post)' },
  { value: 'sanhuwuliu', label: '叁虎物流' },
  { value: 'sunjex', label: '新杰物流' },
  { value: 'hkems', label: '云邮跨境快递' },
  { value: 'anxl', label: '安迅物流' },
  { value: 'transrush', label: 'TransRush' },
  { value: 'huisenky', label: '汇森速运' },
  { value: 'weitepai', label: '微特派' },
  { value: 'arkexpress', label: '方舟速递' },
  { value: 'ocs', label: 'OCS' },
  { value: 'tiandihuayu', label: '天地华宇' },
  { value: 'suteng', label: '广东速腾物流' },
  { value: 'lbex', label: '龙邦物流' },
  { value: 'zhengyikuaidi', label: '鑫正一快递' },
  { value: 'rlgaus', label: '澳洲飞跃物流' },
  { value: 'ane66', label: '安能快递' },
  { value: 'superb', label: 'Superb Grace' },
  { value: 'savor', label: '海信物流' },
  { value: 'xlobo', label: 'Xlobo贝海国际' },
  { value: 'pingandatengfei', label: '平安达腾飞' },
  { value: 'banma', label: '斑马物流' },
  { value: 'ftd', label: '富腾达国际货运' },
  { value: 'crazyexpress', label: '疯狂快递' },
  { value: 'polarexpress', label: '极地快递' },
  { value: 'zhonghuan', label: '中环快递' },
  { value: 'sdto', label: '速达通' },
  { value: 'bflg', label: '上海缤纷物流' },
  { value: 'unitedex', label: '联合速运' },
  { value: 'tnten', label: 'TNT-全球件' },
  { value: 'sfwl', label: '盛丰物流' },
  { value: 'labelway', label: '美通' },
  { value: 'zhongtiewuliu', label: '中铁物流' },
  { value: 'austa', label: 'Austa国际速递' },
  { value: 'dechuangwuliu', label: '深圳德创物流' },
  { value: 'jiayunmeiwuliu', label: '加运美' },
  { value: 'auod', label: '澳德物流' },
  { value: 'bpost', label: '比利时（Bpost）' },
  { value: 'shenghuiwuliu', label: '盛辉物流' },
  { value: 'zhongtongphone', label: '中通（带电话）' },
  { value: 'tianma', label: '天马迅达' },
  { value: 'guangdongyouzhengwuliu', label: '广东邮政' },
  { value: 'wanxiangwuliu', label: '万象物流' },
  { value: 'lianbangkuaidien', label: '联邦快递-英文' },
  { value: 'hkpost', label: '中国香港(HongKong Post)' },
  { value: 'wanjiawuliu', label: '万家物流' },
  { value: 'huangmajia', label: '黄马甲' },
  { value: 'yuntong', label: '运通速运' },
  { value: 'postnlcn', label: '荷兰邮政-中文(PostNL international registered mail)' },
  { value: 'lijisong', label: '成都立即送' },
  { value: 'adapost', label: '安达速递' },
  { value: 'ucs', label: '合众速递(UCS）' },
  { value: 'rufengda', label: '如风达' },
  { value: 'ycgky', label: '远成快运' },
  { value: 'zhongsukuaidi', label: '中速快递' },
  { value: 'sut56', label: '速通物流' },
  { value: 'hengluwuliu', label: '恒路物流' },
  { value: 'aae', label: 'AAE-中国件' },
  { value: 'chukou1', label: '出口易' },
  { value: 'qexpress', label: '易达通快递' },
  { value: 'datianwuliu', label: '大田物流' },
  { value: 'aramex', label: 'Aramex' },
  { value: 'stosolution', label: '申通国际' },
  { value: 'stoexpress', label: '美国申通' },
  { value: 'ueq', label: 'UEQ快递' },
  { value: 'dpd', label: 'DPD' },
  { value: 'baifudongfang', label: '百福东方' },
  { value: 'jingshun', label: '景顺物流' },
  { value: 'doortodoor', label: 'CJ物流' },
  { value: 'zjstky', label: '苏通快运' },
  { value: 'haidaibao', label: '海带宝' },
  { value: 'pjbest', label: '品骏快递' },
  { value: 'ubuy', label: '德国优拜物流' },
  { value: 'dekuncn', label: '德坤物流' },
  { value: 'chnexp', label: '中翼国际物流' },
  { value: 'fastgoexpress', label: '速派快递' },
  { value: 'changjiang', label: '长江国际速递' },
  { value: 'est365', label: '东方汇' },
  { value: 'emsinten', label: 'EMS-国际件-英文' },
  { value: 'bazirim', label: '皮牙子快递' },
  { value: 'uszcn', label: '转运中国' },
  { value: 'jinan', label: '金岸物流' },
  { value: 'singpost', label: '新加坡小包(Singapore Post)' },
  { value: 'xunsuexpress', label: '迅速快递' },
  { value: 'emsen', label: 'EMS-英文' },
  { value: 'tstexp', label: 'TST速运通' },
  { value: 'tntau', label: 'TNT Australia' },
  { value: 'hd', label: '宏递快运' },
  { value: 'newzealand', label: '新西兰（New Zealand Post）' },
  { value: 'oneexpress', label: '一速递' },
  { value: 'yuananda', label: '源安达' },
  { value: 'bsht', label: '百事亨通' },
  { value: 'shangqiao56', label: '商桥物流' },
  { value: 'jumstc', label: '聚盟共建' },
  { value: 'guexp', label: '全联速运' },
  { value: 'xdexpress', label: '迅达速递' },
  { value: 'huanqiu', label: '环球速运' },
  { value: 'fedexcn', label: 'Fedex-国际件-中文' },
  { value: 'zhaijibian', label: '宅急便' },
  { value: 'sujievip', label: '郑州速捷' },
  { value: 'yangbaoguo', label: '洋包裹' },
  { value: 'la911', label: '鼎润物流' },
  { value: 'ontrac', label: 'OnTrac' },
  { value: 'zengyisudi', label: '增益速递' },
  { value: 'meixi', label: '美西快递' },
  { value: 'jxfex', label: '集先锋快递' },
  { value: 'coe', label: 'COE' },
  { value: 'hnht56', label: '鸿泰物流' },
  { value: 'youyou', label: '优优速递' },
  { value: 'yzswuliu', label: '亚洲顺物流' },
  { value: 'sendtochina', label: '速递中国' },
  { value: 'sd138', label: '泰国138国际物流' },
  { value: 'ytkd', label: '运通中港快递' },
  { value: 'quanfengkuaidi', label: '全峰快递' },
  { value: 'euasia', label: '欧亚专线' },
  { value: 'exfresh', label: '安鲜达' },
  { value: 'aotsd', label: '澳天速运' },
  { value: 'epanex', label: '泛捷国际速递' },
  { value: 'cnpex', label: 'CNPEX中邮快递' },
  { value: 'fedexus', label: 'FedEx-美国件' },
  { value: 'westwing', label: '西翼物流' },
  { value: 'haizhongzhuanyun', label: '海中转运' },
  { value: 'yafengsudi', label: '亚风速递' },
  { value: 'canpost', label: '加拿大(Canada Post)' },
  { value: 'dpex', label: 'DPEX' },
  { value: 'deutschepost', label: '德国(Deutsche Post)' },
  { value: 'anxindakuaixi', label: '安信达' },
  { value: 'jiayiwuliu', label: '佳怡物流' },
  { value: 'jialidatong', label: '嘉里大通' },
  { value: 'jgwl', label: '景光物流' },
  { value: 'zlink', label: '三真驿道' },
  { value: 'jiguang', label: '极光转运' },
  { value: 'beckygo', label: '佰麒快递' },
  { value: 'xynyc', label: '新元国际' },
  { value: 'zlxdjwl', label: '中粮鲜到家物流' },
  { value: 'dfkuaidi', label: '东风快递' },
  { value: 'lfexpress', label: '龙枫国际快递' },
  { value: 'correosdees', label: '西班牙(Correos de Espa?a)' },
  { value: 'yaofeikuaidi', label: '耀飞同城快递' },
  { value: 'yunfeng56', label: '韵丰物流' },
  { value: 'colissimo', label: '法国小包（colissimo）' },
  { value: 'httx56', label: '汇通天下物流' },
  { value: 'koalaexp', label: '考拉速递' },
  { value: 'shunfengkuaiyun', label: '顺丰快运' },
  { value: 'hac56', label: '瀚朝物流' },
  { value: 'hexinexpress', label: '合心速递' },
  { value: 'hrex', label: '锦程快递' },
  { value: 'longfx', label: 'LUCFLOW EXPRESS' },
  { value: 'jiajiwuliu', label: '佳吉快运' },
  { value: 'yousutongda', label: '优速通达' },
  { value: 'tcat', label: '黑猫宅急便' },
  { value: 'koreapost', label: '韩国（Korea Post）' },
  { value: 'nzzto', label: '新西兰中通' },
  { value: 'dhlbenelux', label: 'DHL Benelux' },
  { value: 'lasership', label: 'LaserShip' },
  { value: 'efs', label: 'EFS Post（平安快递）' },
  { value: 'cnexps', label: 'CNE' },
  { value: 'tcxbthai', label: 'TCXB国际物流' },
  { value: 'shunfenghk', label: '顺丰-繁体' },
  { value: 'gotoubi', label: 'UBI Australia' },
  { value: 'shipgce', label: '飞洋快递' },
  { value: 'parcelforce', label: '英国大包、EMS（Parcel Force）' },
  { value: 'mosuda', label: '魔速达' },
  { value: 'italiane', label: '意大利(Poste Italiane)' },
  { value: 'sagawa', label: '佐川急便' },
  { value: 'ytchengnuoda', label: '承诺达' },
  { value: 'ftky365', label: '丰通快运' },
  { value: 'tzky', label: '铁中快运' },
  { value: 'ecmscn', label: '易客满' },
  { value: 'yizhengdasuyun', label: '一正达速运' },
  { value: 'topspeedex', label: '中运全速' },
  { value: 'chszhonghuanguoji', label: 'CHS中环国际快递' },
  { value: 'csuivi', label: '法国(La Poste)' },
  { value: 'quanyikuaidi', label: '全一快递' },
  { value: 'com1express', label: '商壹国际物流' },
  { value: 'dpexen', label: 'Toll' },
  { value: 'amazoncnorder', label: '亚马逊中国订单' },
  { value: 'synship', label: 'SYNSHIP快递' },
  { value: 'feiyuanvipshop', label: '飞远配送' },
  { value: 'zhongchuan', label: '众川国际' },
  { value: 'lineone', label: '一号线' },
  { value: 'qinyuan', label: '秦远物流' },
  { value: 'anjie88', label: '安捷物流' },
  { value: 'ganzhongnengda', label: '能达速递' },
  { value: 'shangda', label: '上大物流' },
  { value: 'zteexpress', label: 'ZTE中兴物流' },
  { value: 'jiujiuwl', label: '久久物流' },
  { value: 'tnjex', label: '明通国际快递' },
  { value: 'jiajiawl', label: '加佳物流' },
  { value: 'kingfreight', label: '货运皇' },
  { value: 'minghangkuaidi', label: '民航快递' },
  { value: 'quansutong', label: '全速通' },
  { value: 'wherexpess', label: '威盛快递' },
  { value: 'dayangwuliu', label: '大洋物流' },
  { value: 'ruidianyouzheng', label: '瑞典（Sweden Post）' },
  { value: 'tywl99', label: '天翼物流' },
  { value: 'hlyex', label: '好来运' },
  { value: 'baitengwuliu', label: '百腾物流' },
  { value: 'nanjingshengbang', label: '晟邦物流' },
  { value: 'ndwl', label: '南方传媒物流' },
  { value: 'sundarexpress', label: '顺达快递' },
  { value: 'wuliuky', label: '五六快运' },
  { value: 'peisihuoyunkuaidi', label: '配思货运' },
  { value: 'japanpost', label: '日本郵便' },
  { value: 'cnausu', label: '中澳速递' },
  { value: 'beebird', label: '锋鸟物流' },
  { value: 'cameroon', label: '喀麦隆(CAMPOST)' },
  { value: 'idamalu', label: '大马鹿' },
  { value: 'jiacheng', label: '佳成快递 ' },
  { value: 'shangcheng', label: '尚橙物流' },
  { value: 'postnl', label: '荷兰邮政(PostNL international registered mail)' },
  { value: 'trakpak', label: 'TRAKPAK' },
  { value: 'chengpei', label: '河北橙配' },
  { value: 'jiajikuaidi', label: '佳吉快递' },
  { value: 'spring56', label: '春风物流' },
  { value: 'speedpost', label: '新加坡EMS、大包(Singapore Speedpost)' },
  { value: 'cosco', label: '中远e环球' },
  { value: 'nebuex', label: '星云速递' },
  { value: 'shlindao', label: '林道国际快递' },
  { value: 'sxexpress', label: '三象速递' },
  { value: 'thailand', label: '泰国（Thailand Thai Post）' },
  { value: 'airpak', label: 'airpak expresss' },
  { value: 'malaysiapost', label: '马来西亚小包（Malaysia Post(Registered)）' },
  { value: 'qpost', label: '卡塔尔（Qatar Post）' },
  { value: 'wlwex', label: '星空国际' },
  { value: 'asendiausa', label: 'Asendia USA' },
  { value: 'uscbexpress', label: '易境达国际物流' },
  { value: 'postserv', label: '台湾（中华邮政）' },
  { value: 'tmwexpress', label: '明达国际速递' },
  { value: 'ukrpostcn', label: '乌克兰邮政包裹' },
  { value: 'jieanda', label: '捷安达' },
  { value: 'emswuliu', label: 'EMS物流' },
  { value: 'onehcang', label: '一号仓' },
  { value: 'chengtong', label: '城通物流' },
  { value: 'exsuda', label: 'E速达' },
  { value: 'hermes', label: 'Hermes' },
  { value: 'tykd', label: '天翼快递' },
  { value: 'gxwl', label: '光线速递' },
  { value: 'taoplus', label: '淘布斯国际物流' },
  { value: 'wjkwl', label: '万家康物流' },
  { value: 'globaltracktrace', label: 'globaltracktrace' },
  { value: 'gts', label: 'GTS快递' },
  { value: 'wykjt', label: '51跨境通' },
  { value: 'cllexpress', label: '澳通华人物流' },
  { value: 'xiyoug', label: '西游寄' },
  { value: 'wtdchina', label: '威时沛运货运' },
  { value: 'anposten', label: '爱尔兰(An Post)' },
  { value: 'dhlde', label: 'DHL-德国件（DHL Deutschland）' },
  { value: 'hre', label: '高铁速递' },
  { value: 'jiazhoumao', label: '加州猫速递' },
  { value: 'shpostwish', label: 'wish邮' },
  { value: 'a2u', label: 'A2U速递' },
  { value: 'flysman', label: '飞力士物流' },
  { value: 'slovenia', label: '斯洛文尼亚(Slovenia Post)' },
  { value: 'yidatong', label: '易达通' },
  { value: 'yufeng', label: '御风速运' },
  { value: 'zhongtianwanyun', label: '中天万运' },
  { value: 'cht361', label: '诚和通' },
  { value: 'mmlogi', label: '猛犸速递' },
  { value: 'pcaexpress', label: 'PCA Express' },
  { value: 'feikangda', label: '飞康达' },
  { value: 'gsm', label: 'GSM' },
  { value: 'yingchao', label: '英超物流' },
  { value: 'youban', label: '邮邦国际' },
  { value: 'uspscn', label: 'USPSCN' },
  { value: 'bht', label: 'BHT' },
  { value: 'dfwl', label: '达发物流' },
  { value: 'heimao56', label: '黑猫速运' },
  { value: 'szyouzheng', label: '深圳邮政' },
  { value: 'guoeryue', label: '天天快物流' },
  { value: 'hltop', label: '海联快递' },
  { value: 'morelink56', label: 'MoreLink' },
  { value: 'uhi', label: '优海国际速递' },
  { value: 'chuangyi', label: '创一快递' },
  { value: 'ht22', label: '海淘物流' },
  { value: 'nederlandpost', label: '荷兰速递(Nederland Post)' },
  { value: 'zf365', label: '珠峰速运' },
  { value: 'zhongjiwuliu', label: '中技物流' },
  { value: 'zsky123', label: '准实快运' },
  { value: 'pochta', label: '俄罗斯邮政(Russian Post)' },
  { value: 'vps', label: '维普恩物流' },
  { value: 'aolau', label: 'AOL澳通速递' },
  { value: 'bulgarian', label: '保加利亚（Bulgarian Posts）' },
  { value: 'quanjitong', label: '全际通' },
  { value: 'bjemstckj', label: '北京EMS' },
  { value: 'zhonghuanus', label: '中环转运' },
  { value: 'easyexpress', label: 'EASY EXPRESS' },
  { value: 'newsway', label: '家家通快递' },
  { value: 'dingdong', label: '叮咚快递' },
  { value: 'mingliangwuliu', label: '明亮物流' },
  { value: 'postnlchina', label: '荷兰邮政-中国件' },
  { value: 'boyol', label: '贝业物流' },
  { value: 'eshunda', label: '俄顺达' },
  { value: 'shenganwuliu', label: '圣安物流' },
  { value: 'meiguokuaidi', label: '美国快递' },
  { value: 'qbexpress', label: '秦邦快运' },
  { value: 'wto56kj', label: '臣邦同城' },
  { value: 'ztong', label: '智通物流' },
  { value: 'benteng', label: '奔腾物流' },
  { value: 'chuanxiwuliu', label: '传喜物流' },
  { value: 'etong', label: 'E通速递' },
  { value: 'kenya', label: '肯尼亚(POSTA KENYA)' },
  { value: 'nell', label: '尼尔快递' },
  { value: 'pfcexpress', label: '皇家物流' },
  { value: 'swisspost', label: '瑞士(Swiss Post)' },
  { value: 'zdepost', label: '直德邮' },
  { value: 'bangsongwuliu', label: '邦送物流' },
  { value: 'hnfy', label: '飞鹰物流' },
  { value: 'jcsuda', label: '嘉诚速达' },
  { value: 'jixianda', label: '急先达' },
  { value: 'trackparcel', label: 'track-parcel' },
  { value: 'abf', label: 'ABF' },
  { value: 'emms', label: '澳州顺风快递' },
  { value: 'hhair56', label: '华瀚快递' },
  { value: 'hkposten', label: '中国香港(HongKong Post)英文' },
  { value: 'hongywl', label: '红远物流' },
  { value: 'postnlpacle', label: '荷兰包裹(PostNL International Parcels)' },
  { value: 'szuem', label: '联运通物流' },
  { value: 'byht', label: '展勤快递' },
  { value: 'homecourier', label: '如家国际快递' },
  { value: 'minbangsudi', label: '民邦速递' },
  { value: 'santaisudi', label: '三态速递' },
  { value: 'hangrui', label: '上海航瑞货运' },
  { value: 'ztjieda', label: '泰捷达国际物流' },
  { value: 'adp', label: 'ADP国际快递' },
  { value: 'astexpress', label: '安世通快递' },
  { value: 'chunghwa56', label: '中骅物流' },
  { value: 'farlogistis', label: '泛远国际物流' },
  { value: 'kerrytj', label: '嘉里大荣物流' },
  { value: 'sccod', label: '丰程物流' },
  { value: 'shunjieda', label: '顺捷达' },
  { value: 'yongchangwuliu', label: '永昌物流' },
  { value: 'anjiekuaidi', label: '青岛安捷快递' },
  { value: 'blueskyexpress', label: '蓝天快递' },
  { value: 'ctoexp', label: '泰国中通CTO' },
  { value: 'fanyukuaidi', label: '凡宇快递' },
  { value: 'jieborne', label: '捷邦物流' },
  { value: 'luben', label: '陆本速递 LUBEN EXPRESS' },
  { value: 'parcelforcecn', label: '英国邮政大包EMS' },
  { value: 'signedexpress', label: '签收快递' },
  { value: 'sunspeedy', label: '新速航' },
  { value: 'vnpost', label: '越南EMS(VNPost Express)' },
  { value: 'ydhex', label: 'YDH' },
  { value: 'zsmhwl', label: '明辉物流' },
  { value: 'chinapostcb', label: '中邮电商' },
  { value: 'rrskx', label: '日日顺快线' },
  { value: 'yuefengwuliu', label: '越丰物流' },
  { value: 'biaojikuaidi', label: '彪记快递' },
  { value: 'citylink', label: 'City-Link' },
  { value: 'gongsuda', label: '共速达' },
  { value: 'gslexpress', label: '德尚国际速递' },
  { value: 'kejie', label: '科捷物流' },
  { value: 'fbkd', label: '飞邦快递' },
  { value: 'feibaokuaidi', label: '飞豹快递' },
  { value: 'kaolaexpress', label: '考拉国际速递' },
  { value: 'ltx', label: '蓝天国际快递' },
  { value: 'shunjiefengda', label: '顺捷丰达' },
  { value: 'ydglobe', label: '云达通' },
  { value: 'yuntongkuaidi', label: '运通中港' },
  { value: 'bdatong', label: '八达通' },
  { value: 'bluedart', label: 'BlueDart' },
  { value: 'bpostinter', label: '比利时国际(Bpost international)' },
  { value: 'disifangau', label: '递四方澳洲' },
  { value: 'eupackage', label: '易优包裹' },
  { value: 'goldjet', label: '高捷快运' },
  { value: 'jamaicapost', label: '牙买加（Jamaica Post）' },
  { value: 'longcps', label: '加拿大龙行速运' },
  { value: 'yue777', label: '玥玛速运' },
  { value: 'yujiawl', label: '宇佳物流' },
  { value: '1ziton', label: '一智通' },
  { value: 'advancing', label: '安达信' },
  { value: 'buytong', label: '百通物流' },
  { value: 'fengyee', label: '丰羿' },
  { value: 'fox', label: 'FOX国际快递' },
  { value: 'huaqikuaiyun', label: '华企快运' },
  { value: 'jdiex', label: 'JDIEX' },
  { value: 'myhermes', label: 'MyHermes' },
  { value: 'qichen', label: '启辰国际速递' },
  { value: 'ynztsy', label: '纵通速运' },
  { value: 'zsda56', label: '转瞬达集运' },
  { value: 'belgiumpost', label: '比利时(Belgium Post)' },
  { value: 'changyuwuliu', label: '长宇物流' },
  { value: 'cnspeedster', label: '速舟物流' },
  { value: 'gooday365', label: '日日顺智慧物联' },
  { value: 'macao', label: '中国澳门(Macau Post)' },
  { value: 'yuanfeihangwuliu', label: '原飞航' },
  { value: 'adaexpress', label: '明大快递' },
  { value: 'fastontime', label: '加拿大联通快运' },
  { value: 'ghtexpress', label: 'GHT物流' },
  { value: 'quanritongkuaidi', label: '全日通' },
  { value: 'saiaodimmb', label: '赛澳递for买卖宝' },
  { value: 'sfift', label: '十方通物流' },
  { value: 'tonghetianxia', label: '通和天下' },
  { value: 'xianglongyuntong', label: '祥龙运通物流' },
  { value: 'yundaexus', label: '美国云达' },
  { value: 'abcglobal', label: '全球快运' },
  { value: 'airgtc', label: '航空快递' },
  { value: 'bee001', label: '蜜蜂速递' },
  { value: 'canhold', label: '能装能送' },
  { value: 'cces', label: 'CCES/国通快递' },
  { value: 'comexpress', label: '邦通国际' },
  { value: 'dadaoex', label: '大道物流' },
  { value: 'dongjun', label: '成都东骏物流' },
  { value: 'efspost', label: 'EFSPOST' },
  { value: 'haihongwangsong', label: '海红网送' },
  { value: 'humpline', label: '驼峰国际' },
  { value: 'hungary', label: '匈牙利（Magyar Posta）' },
  { value: 'jcex', label: 'jcex' },
  { value: 'malaysiaems', label: '马来西亚大包、EMS（Malaysia Post(parcel,EMS)）' },
  { value: 'pakistan', label: '巴基斯坦(Pakistan Post)' },
  { value: 'pengyuanexpress', label: '鹏远国际速递' },
  { value: 'quansu', label: '全速物流' },
  { value: 'riyuwuliu', label: '日昱物流' },
  { value: 'tntuk', label: 'TNT UK' },
  { value: 'xsrd', label: '鑫世锐达' },
  { value: 'yiqisong', label: '一起送' },
  { value: 'yuanzhijiecheng', label: '元智捷诚' },
  { value: 'adlerlogi', label: '德国雄鹰速递' },
  { value: 'ahdf', label: '德方物流' },
  { value: 'ahkbps', label: '卡邦配送' },
  { value: 'chengda', label: '成达国际速递' },
  { value: 'chinatzx', label: '同舟行物流' },
  { value: 'dhlhk', label: 'DHL HK' },
  { value: 'diantongkuaidi', label: '店通快递' },
  { value: 'feihukuaidi', label: '飞狐快递' },
  { value: 'hotwms', label: '皇家云仓' },
  { value: 'india', label: '印度(India Post)' },
  { value: 'jindawuliu', label: '金大物流' },
  { value: 'mchy', label: '木春货运' },
  { value: 'quanchuan56', label: '全川物流' },
  { value: 'saiaodi', label: '赛澳递' },
  { value: 'sinoairinex', label: '中外运空运' },
  { value: 'sxhongmajia', label: '红马甲物流' },
  { value: 'zjgj56', label: '振捷国际货运' },
  { value: 'ajexpress', label: '捷记方舟' },
  { value: 'albania', label: '阿尔巴尼亚(Posta shqipatre)' },
  { value: 'alog', label: '心怡物流' },
  { value: 'aplusex', label: 'Aplus物流' },
  { value: 'auex', label: '澳货通' },
  { value: 'ausbondexpress', label: '澳邦国际物流' },
  { value: 'ausexpress', label: '澳世速递' },
  { value: 'canpostfr', label: '加拿大邮政' },
  { value: 'ckeex', label: '城晓国际快递' },
  { value: 'cnair', label: 'CNAIR' },
  { value: 'dpdgermany', label: 'DPD Germany' },
  { value: 'esinotrans', label: '中外运' },
  { value: 'euexpress', label: 'EU-EXPRESS' },
  { value: 'euguoji', label: '易邮国际' },
  { value: 'fenghuangkuaidi', label: '凤凰快递' },
  { value: 'freakyquick', label: 'FQ狂派速递' },
  { value: 'gdkjk56', label: '快捷快物流' },
  { value: 'hongbeixin', label: '红背心' },
  { value: 'huanqiuabc', label: '中国香港环球快运' },
  { value: 'idada', label: '大达物流' },
  { value: 'iyoungspeed', label: '驿扬国际速运' },
  { value: 'kcs', label: 'KCS' },
  { value: 'lesotho', label: '莱索托(Lesotho Post)' },
  { value: 'parcelchina', label: '诚一物流' },
  { value: 'pengcheng', label: '鹏程快递' },
  { value: 'qianli', label: '千里速递' },
  { value: 'rpx', label: 'rpx' },
  { value: 'sdsy888', label: '首达速运' },
  { value: 'shunbang', label: '顺邦国际物流' },
  { value: 'southafrican', label: '南非（South African Post Office）' },
  { value: 'stkd', label: '顺通快递' },
  { value: 'tongdaxing', label: '通达兴物流' },
  { value: 'yinjiesudi', label: '银捷速递' },
  { value: 'yyqc56', label: '一运全成物流' },
  { value: 'zhongxinda', label: '忠信达' },
  { value: 'auvanda', label: '中联速递' },
  { value: 'baishiyp', label: '百世云配' },
  { value: 'bangladesh', label: '孟加拉国(EMS)' },
  { value: 'barbados', label: '巴巴多斯(Barbados Post)' },
  { value: 'belize', label: '伯利兹(Belize Postal)' },
  { value: 'bjxsrd', label: '鑫锐达' },
  { value: 'cncexp', label: 'C&C国际速递' },
  { value: 'dhlecommerce', label: 'dhl小包' },
  { value: 'dhlnetherlands', label: 'DHL-荷兰（DHL Netherlands）' },
  { value: 'didasuyun', label: '递达速运' },
  { value: 'edtexpress', label: 'e直运' },
  { value: 'express7th', label: '7号速递' },
  { value: 'feikuaida', label: '飞快达' },
  { value: 'haimengsudi', label: '海盟速递' },
  { value: 'haoyoukuai', label: '好又快物流' },
  { value: 'hmus', label: '华美快递' },
  { value: 'huoban', label: '兰州伙伴物流' },
  { value: 'hyytes', label: '恒宇运通' },
  { value: 'iparcel', label: 'UPS i-parcel' },
  { value: 'juding', label: '聚鼎物流' },
  { value: 'kazpost', label: '哈萨克斯坦(Kazpost)' },
  { value: 'luckyfastex', label: '吉捷国际速递' },
  { value: 'namibia', label: '纳米比亚(NamPost)' },
  { value: 'newgistics', label: 'Newgistics' },
  { value: 'postpng', label: '巴布亚新几内亚(PNG Post)' },
  { value: 'purolator', label: 'Purolator' },
  { value: 'taijin', label: '泰进物流' },
  { value: 'uzbekistan', label: '乌兹别克斯坦(Post of Uzbekistan)' },
  { value: 'vangenexpress', label: '万庚国际速递' },
  { value: 'wandougongzhu', label: '豌豆物流' },
  { value: 'xiangdawuliu', label: '湘达物流' },
  { value: 'xiaocex', label: '小C海淘' },
  { value: 'yiex', label: '宜送物流' },
  { value: 'yiouzhou', label: '易欧洲国际物流' },
  { value: 'yodel', label: 'YODEL' },
  { value: 'ytky168', label: '运通快运' },
  { value: 'yuanhhk', label: '远航国际快运' },
  { value: 'yuezhongsh', label: '粤中国际货运代理（上海）有限公司' },
  { value: 'zhdwl', label: '众辉达物流' },
  { value: 'zhongwaiyun', label: '中外运速递' },
  { value: 'amusorder', label: 'amazon-国际订单' },
  { value: 'aosu', label: '澳速物流' },
  { value: 'bangbangpost', label: '帮帮发' },
  { value: 'belpost', label: '白俄罗斯(Belpochta)' },
  { value: 'benniao', label: '笨鸟国际' },
  { value: 'bester', label: '飛斯特' },
  { value: 'bqcwl', label: '百千诚物流' },
  { value: 'cambodia', label: '柬埔寨(Cambodia Post)' },
  { value: 'ceskaposta', label: '捷克（?eská po?ta）' },
  { value: 'cevalogistics', label: 'CEVA Logistic' },
  { value: 'cfss', label: '银雁专送' },
  { value: 'changwooair', label: '昌宇国际' },
  { value: 'chinasqk', label: 'SQK国际速递' },
  { value: 'chronopostfra', label: '法国大包、EMS-法文（Chronopost France）' },
  { value: 'correos', label: '哥斯达黎加(Correos de Costa Rica)' },
  { value: 'czwlyn', label: '云南诚中物流' },
  { value: 'dfpost', label: '达方物流' },
  { value: 'donghong', label: '东红物流' },
  { value: 'dpdpoland', label: 'DPD Poland' },
  { value: 'el56', label: '易联通达' },
  { value: 'emsukrainecn', label: '乌克兰EMS-中文(EMS Ukraine)' },
  { value: 'eucpost', label: '德国 EUC POST' },
  { value: 'eusacn', label: '优莎速运' },
  { value: 'excocotree', label: '可可树美中速运' },
  { value: 'fedroad', label: 'FedRoad 联邦转运' },
  { value: 'fiji', label: '斐济(Fiji Post)' },
  { value: 'fyex', label: '飞云快递系统' },
  { value: 'gda', label: '安的快递' },
  { value: 'ghl', label: '环创物流' },
  { value: 'gttexpress', label: 'GTT EXPRESS快递' },
  { value: 'hangyu', label: '航宇快递' },
  { value: 'happylink', label: '开心快递' },
  { value: 'huada', label: '华达快运' },
  { value: 'huaxiahuoyun', label: '华夏货运' },
  { value: 'jiachenexpress', label: '佳辰国际速递' },
  { value: 'jjx888', label: '佳捷翔物流' },
  { value: 'junfengguoji', label: '骏丰国际速递' },
  { value: 'kjde', label: '跨境直邮通' },
  { value: 'koreapostcn', label: '韩国邮政' },
  { value: 'kuai8', label: '快8速运' },
  { value: 'ledaowuliu', label: '楽道物流' },
  { value: 'lithuania', label: '立陶宛（Lietuvos pa?tas）' },
  { value: 'littlebearbear', label: '小熊物流' },
  { value: 'longlangkuaidi', label: '隆浪快递' },
  { value: 'longvast', label: '长风物流' },
  { value: 'lsexpress', label: '6LS EXPRESS' },
  { value: 'maxeedexpress', label: '澳洲迈速快递' },
  { value: 'moldova', label: '摩尔多瓦(Posta Moldovei)' },
  { value: 'montenegro', label: '黑山(Posta Crne Gore)' },
  { value: 'nlebv', label: '亚欧专线' },
  { value: 'ocaargen', label: 'OCA Argentina' },
  { value: 'posta', label: '坦桑尼亚（Tanzania Posts Corporation）' },
  { value: 'sanshengco', label: '三盛快递' },
  { value: 'scic', label: '中加国际快递' },
  { value: 'sczpds', label: '速呈' },
  { value: 'sfjhd', label: '圣飞捷快递' },
  { value: 'shunshid', label: '顺士达速运' },
  { value: 'skynetmalaysia', label: 'SkyNet Malaysia' },
  { value: 'sucmj', label: '特急便物流' },
  { value: 'suijiawuliu', label: '穗佳物流' },
  { value: 'swisspostcn', label: '瑞士邮政' },
  { value: 'szshihuatong56', label: '世华通物流' },
  { value: 'thaizto', label: '泰国中通ZTO' },
  { value: 'tianxiang', label: '天翔快递' },
  { value: 'tianzong', label: '天纵物流' },
  { value: 'tollpriority', label: 'Toll Priority(Toll Online)' },
  { value: 'turtle', label: '海龟国际快递' },
  { value: 'uexiex', label: '欧洲UEX' },
  { value: 'ugoexpress', label: '邮鸽速运' },
  { value: 'uluckex', label: '优联吉运' },
  { value: 'upsfreight', label: 'UPS Freight' },
  { value: 'vctrans', label: '越中国际物流' },
  { value: 'wenjiesudi', label: '文捷航空' },
  { value: 'wlfast', label: '凡仕特物流' },
  { value: 'yamaxunwuliu', label: '亚马逊中国' },
  { value: 'yemen', label: '也门(Yemen Post)' },
  { value: 'yhtlogistics', label: '宇航通物流' },
  { value: 'yifankd', label: '艺凡快递' },
  { value: 'yitongda', label: '易通达' },
  { value: 'youlai', label: '邮来速递' },
  { value: 'ypsd', label: '壹品速递' },
  { value: 'yunexpress', label: '德国云快递' },
  { value: 'yw56', label: '燕文物流' },
  { value: 'yyexp', label: '西安运逸快递' },
  { value: 'zhpex', label: '众派速递' },
  { value: 'adiexpress', label: '安达易国际速递' },
  { value: 'afghan', label: '阿富汗(Afghan Post)' },
  { value: 'afl', label: 'AFL' },
  { value: 'agopost', label: '全程快递' },
  { value: 'aliexpress', label: '无忧物流' },
  { value: 'amcnorder', label: 'amazon-国内订单' },
  { value: 'anjiatongcheng', label: '安家同城快运' },
  { value: 'anlexpress', label: '新干线快递' },
  { value: 'apgecommerce', label: 'apgecommerce' },
  { value: 'aplus100', label: '美国汉邦快递' },
  { value: 'ariesfar', label: '艾瑞斯远' },
  { value: 'aruba', label: '阿鲁巴[荷兰]（Post Aruba）' },
  { value: 'austria', label: '奥地利(Austrian Post)' },
  { value: 'auvexpress', label: 'AUV国际快递' },
  { value: 'axexpress', label: '澳新物流' },
  { value: 'azerbaijan', label: '阿塞拜疆EMS(EMS AzerExpressPost)' },
  { value: 'bahrain', label: '巴林(Bahrain Post)' },
  { value: 'baotongkd', label: '宝通快递' },
  { value: 'baoxianda', label: '报通快递' },
  { value: 'bcwelt', label: 'BCWELT' },
  { value: 'bjqywl', label: '青云物流' },
  { value: 'bmlchina', label: '标杆物流' },
  { value: 'bohei', label: '波黑(JP BH Posta)' },
  { value: 'bolivia', label: '玻利维亚' },
  { value: 'borderguru', label: 'BorderGuru' },
  { value: 'bosind', label: '堡昕德速递' },
  { value: 'botspost', label: '博茨瓦纳' },
  { value: 'bphchina', label: '速方(Sufast)' },
  { value: 'brazilposten', label: '巴西(Brazil Post/Correios)' },
  { value: 'brunei', label: '文莱(Brunei Postal)' },
  { value: 'caledonia', label: '新喀里多尼亚[法国](New Caledonia)' },
  { value: 'camekong', label: '到了港' },
  { value: 'campbellsexpress', label: 'Campbell’s Express' },
  { value: 'canpar', label: 'Canpar' },
  { value: 'cargolux', label: '卢森堡航空' },
  { value: 'cbo56', label: '钏博物流' },
  { value: 'cccc58', label: '中集冷云' },
  { value: 'ccd', label: '河南次晨达' },
  { value: 'cdek', label: 'CDEK' },
  { value: 'cdxinchen56', label: '鑫宸物流' },
  { value: 'cex', label: '城铁速递' },
  { value: 'chengji', label: '城际快递' },
  { value: 'chile', label: '智利(Correos Chile)' },
  { value: 'chinastarlogistics', label: '华欣物流' },
  { value: 'chllog', label: '嘉荣物流' },
  { value: 'chronopostfren', label: '法国大包、EMS-英文(Chronopost France)' },
  { value: 'chronopostport', label: 'Chronopost Portugal' },
  { value: 'chunfai', label: '中国香港骏辉物流' },
  { value: 'city56', label: '城市映急' },
  { value: 'citysprint', label: 'citysprint' },
  { value: 'cjkoreaexpress', label: '大韩通运' },
  { value: 'cloudexpress', label: 'CE易欧通国际速递' },
  { value: 'clsp', label: 'CL日中速运' },
  { value: 'cneulogistics', label: '中欧物流' },
  { value: 'cnup', label: 'CNUP 中联邮' },
  { value: 'cnws', label: '中国翼' },
  { value: 'colombia', label: '哥伦比亚(4-72 La Red Postal de Colombia)' },
  { value: 'correios', label: '莫桑比克（Correios de Moçambique）' },
  { value: 'correo', label: '乌拉圭（Correo Uruguayo）' },
  { value: 'correoargentino', label: '阿根廷(Correo Argentina)' },
  { value: 'cpsair', label: '华中快递' },
  { value: 'cqxingcheng', label: '重庆星程快递' },
  { value: 'crossbox', label: '环旅快运' },
  { value: 'csxss', label: '新时速物流' },
  { value: 'cypruspost', label: '塞浦路斯(Cyprus Post)' },
  { value: 'dande56', label: '丹递56' },
  { value: 'dasu', label: '达速物流' },
  { value: 'dcs', label: 'DCS' },
  { value: 'decnlh', label: '德中快递' },
  { value: 'deltec', label: 'Deltec Courier' },
  { value: 'desworks', label: '澳行快递' },
  { value: 'dhlpoland', label: 'DHL-波兰（DHL Poland）' },
  { value: 'di5pll', label: '递五方云仓' },
  { value: 'dianyi', label: '云南滇驿物流' },
  { value: 'dindon', label: '叮咚澳洲转运' },
  { value: 'directlink', label: 'Direct Link' },
  { value: 'disifangus', label: '递四方美国' },
  { value: 'djy56', label: '天翔东捷运' },
  { value: 'donghanwl', label: '东瀚物流' },
  { value: 'dpduk', label: 'DPD UK' },
  { value: 'dtdcindia', label: 'DTDC India' },
  { value: 'duodao56', label: 'duodao56' },
  { value: 'ealceair', label: '东方航空物流' },
  { value: 'ecallturn', label: 'E跨通' },
  { value: 'ecfirstclass', label: 'EC-Firstclass' },
  { value: 'ecmsglobal', label: 'ECMS Express' },
  { value: 'ecotransite', label: '东西E全运' },
  { value: 'ecuador', label: '厄瓜多尔(Correos del Ecuador)' },
  { value: 'edaeuexpress', label: '易达快运' },
  { value: 'edragon', label: '龙象国际物流' },
  { value: 'egypt', label: '埃及（Egypt Post）' },
  { value: 'eiffel', label: '艾菲尔国际速递' },
  { value: 'elta', label: '希腊包裹（ELTA Hellenic Post）' },
  { value: 'eltahell', label: '希腊EMS（ELTA Courier）' },
  { value: 'emirates', label: '阿联酋(Emirates Post)' },
  { value: 'emonitoring', label: '波兰小包(Poczta Polska)' },
  { value: 'emssouthafrica', label: '南非EMS' },
  { value: 'emsukraine', label: '乌克兰EMS(EMS Ukraine)' },
  { value: 'england', label: '英国(大包,EMS)' },
  { value: 'epspost', label: '联众国际' },
  { value: 'estafeta', label: 'Estafeta' },
  { value: 'estes', label: 'Estes' },
  { value: 'eta100', label: '易达国际速递' },
  { value: 'ethiopia', label: '埃塞俄比亚(Ethiopian postal)' },
  { value: 'eucnrail', label: '中欧国际物流' },
  { value: 'europe8', label: '败欧洲' },
  { value: 'europeanecom', label: 'europeanecom' },
  { value: 'expressplus', label: '澳洲新干线快递' },
  { value: 'ezhuanyuan', label: '易转运' },
  { value: 'fandaguoji', label: '颿达国际快递-英文' },
  { value: 'fardarww', label: '颿达国际快递' },
  { value: 'fastway', label: 'Fastway Ireland' },
  { value: 'fastzt', label: '正途供应链' },
  { value: 'fedexuk', label: 'FedEx-英国件（FedEx UK)' },
  { value: 'fedexukcn', label: 'FedEx-英国件' },
  { value: 'finland', label: '芬兰(Itella Posti Oy)' },
  { value: 'flowerkd', label: '花瓣转运' },
  { value: 'fsexp', label: '全速快递' },
  { value: 'ftlexpress', label: '法翔速运' },
  { value: 'gaotieex', label: '高铁快运' },
  { value: 'gaticn', label: 'Gati-中文' },
  { value: 'gatien', label: 'Gati-英文' },
  { value: 'gatikwe', label: 'Gati-KWE' },
  { value: 'gdct56', label: '广东诚通物流' },
  { value: 'gdqwwl', label: '全网物流' },
  { value: 'gdrz58', label: '容智快运' },
  { value: 'gdxp', label: '新鹏快递' },
  { value: 'ge2d', label: 'GE2D跨境物流' },
  { value: 'georgianpost', label: '格鲁吉亚(Georgian Pos）' },
  { value: 'gibraltar', label: '直布罗陀[英国]( Royal Gibraltar Post)' },
  { value: 'gjwl', label: '冠捷物流 ' },
  { value: 'gls', label: 'GLS' },
  { value: 'gml', label: '英脉物流' },
  { value: 'greenland', label: '格陵兰[丹麦]（TELE Greenland A/S）' },
  { value: 'grivertek', label: '潍鸿' },
  { value: 'gscq365', label: '哥士传奇速递' },
  { value: 'gswtkd', label: '万通快递' },
  { value: 'gtgogo', label: 'GT国际快运' },
  { value: 'gtongsudi', label: '广通速递' },
  { value: 'guangdongtonglu', label: '广东通路' },
  { value: 'guanting', label: '冠庭国际物流' },
  { value: 'guosong', label: '国送快运' },
  { value: 'gvpexpress', label: '宏观国际快递' },
  { value: 'gzxingcheng', label: '贵州星程快递' },
  { value: 'haihongmmb', label: '海红for买卖宝' },
  { value: 'haiwaihuanqiu', label: '海外环球' },
  { value: 'haixingqiao', label: '海星桥快递' },
  { value: 'handboy', label: '汉邦国际速递' },
  { value: 'hanfengjl', label: '翰丰快递' },
  { value: 'haypost', label: '亚美尼亚(Haypost-Armenian Postal)' },
  { value: 'hengrui56', label: '恒瑞物流' },
  { value: 'hgy56', label: '环国运物流' },
  { value: 'highsince', label: 'Highsince' },
  { value: 'hitaoe', label: 'Hi淘易快递' },
  { value: 'hjs', label: '猴急送' },
  { value: 'hlkytj', label: '互联快运' },
  { value: 'hlpgyl', label: '共联配' },
  { value: 'hnqst', label: '河南全速通' },
  { value: 'hnssd56', label: '顺时达物流' },
  { value: 'hnzqwl', label: '中强物流' },
  { value: 'homexpress', label: '居家通' },
  { value: 'hongjie', label: '宏捷国际物流' },
  { value: 'hongpinwuliu', label: '宏品物流' },
  { value: 'hqtd', label: '环球通达 ' },
  { value: 'hrbzykd', label: '卓烨快递' },
  { value: 'hrvatska', label: '克罗地亚（Hrvatska Posta）' },
  { value: 'hsgtsd', label: '海硕高铁速递' },
  { value: 'htongexpress', label: '华通快运' },
  { value: 'htwd', label: '华通务达物流' },
  { value: 'huandonglg', label: '环东物流' },
  { value: 'huiqiangkuaidi', label: '汇强快递' },
  { value: 'hutongwuliu', label: '户通物流' },
  { value: 'hyeship', label: '鸿远物流' },
  { value: 'hyk', label: '上海昊宏国际货物' },
  { value: 'hzpl', label: '华航快递' },
  { value: 'iceland', label: '冰岛(Iceland Post)' },
  { value: 'iexpress', label: 'iExpress' },
  { value: 'ilogen', label: 'logen路坚' },
  { value: 'ilyang', label: 'ILYANG' },
  { value: 'imlb2c', label: '艾姆勒' },
  { value: 'indonesia', label: '印度尼西亚EMS(Pos Indonesia-EMS)' },
  { value: 'inposdom', label: '多米尼加（INPOSDOM – Instituto Postal Dominicano）' },
  { value: 'interlink', label: 'Interlink Express' },
  { value: 'iran', label: '伊朗（Iran Post）' },
  { value: 'israelpost', label: '以色列(Israel Post)' },
  { value: 'italysad', label: 'Italy SDA' },
  { value: 'jdexpressusa', label: '骏达快递' },
  { value: 'jdpplus', label: '急递' },
  { value: 'jerseypost', label: '泽西岛' },
  { value: 'jetexpressgroup', label: '澳速通国际速递' },
  { value: 'jiajiatong56', label: '佳家通货运' },
  { value: 'jinchengwuliu', label: '锦程物流' },
  { value: 'jintongkd', label: '劲通快递' },
  { value: 'jinyuekuaidi', label: '晋越快递' },
  { value: 'jisu', label: '冀速物流' },
  { value: 'jiugong', label: '九宫物流' },
  { value: 'jiuyicn', label: '久易快递' },
  { value: 'jixiangyouau', label: '吉祥邮（澳洲）' },
  { value: 'jordan', label: '约旦(Jordan Post)' },
  { value: 'jsexpress', label: '骏绅物流' },
  { value: 'juwu', label: '聚物物流' },
  { value: 'juzhongda', label: '聚中大' },
  { value: 'kfwnet', label: '快服务' },
  { value: 'khzto', label: '柬埔寨中通' },
  { value: 'koali', label: '番薯国际货运' },
  { value: 'koreapostkr', label: '韩国邮政韩文' },
  { value: 'krtao', label: '淘韩国际快递' },
  { value: 'ksudi', label: '快速递' },
  { value: 'kuaidawuliu', label: '快达物流' },
  { value: 'kuaitao', label: '快淘快递' },
  { value: 'kuaiyouda', label: '四川快优达速递' },
  { value: 'kxda', label: '凯信达' },
  { value: 'kyrgyzpost', label: '吉尔吉斯斯坦(Kyrgyz Post)' },
  { value: 'kyue', label: '跨跃国际' },
  { value: 'lanbiaokuaidi', label: '蓝镖快递' },
  { value: 'landmarkglobal', label: 'Landmark Global' },
  { value: 'lanhukuaidi', label: '蓝弧快递' },
  { value: 'lao', label: '老挝(Lao Express) ' },
  { value: 'laposte', label: '塞内加尔' },
  { value: 'lasy56', label: '林安物流' },
  { value: 'latvia', label: '拉脱维亚(Latvijas Pasts)' },
  { value: 'lbbk', label: '立白宝凯物流' },
  { value: 'ldxpres', label: '林道国际快递-英文' },
  { value: 'ledii', label: '乐递供应链' },
  { value: 'leopard', label: '云豹国际货运' },
  { value: 'letseml', label: '美联快递' },
  { value: 'lgs', label: 'lazada' },
  { value: 'lianyun', label: '联运快递' },
  { value: 'libanpost', label: '黎巴嫩(Liban Post)' },
  { value: 'linex', label: 'Linex' },
  { value: 'lishi', label: '丽狮物流' },
  { value: 'lmfex', label: '良藤国际速递' },
  { value: 'logistics', label: '華信物流WTO' },
  { value: 'lqht', label: '恒通快递' },
  { value: 'ltexp', label: '乐天速递' },
  { value: 'ltparcel', label: '联通快递' },
  { value: 'lundao', label: '论道国际物流' },
  { value: 'lutong', label: '鲁通快运' },
  { value: 'luxembourg', label: '卢森堡(Luxembourg Post)' },
  { value: 'lwe', label: 'LWE' },
  { value: 'macedonia', label: '马其顿(Macedonian Post)' },
  { value: 'mailikuaidi', label: '麦力快递' },
  { value: 'mailongdy', label: '迈隆递运' },
  { value: 'maldives', label: '马尔代夫(Maldives Post)' },
  { value: 'malta', label: '马耳他（Malta Post）' },
  { value: 'mangguo', label: '芒果速递' },
  { value: 'mapleexpress', label: '今枫国际快运' },
  { value: 'mauritius', label: '毛里求斯(Mauritius Post)' },
  { value: 'meibang', label: '美邦国际快递' },
  { value: 'meidaexpress', label: '美达快递' },
  { value: 'meitai', label: '美泰物流' },
  { value: 'mexico', label: '墨西哥（Correos de Mexico）' },
  { value: 'mexicodenda', label: 'Mexico Senda Express' },
  { value: 'milkyway', label: '银河物流' },
  { value: 'mjexp', label: '美龙快递' },
  { value: 'mongolpost', label: '蒙古国(Mongol Post) ' },
  { value: 'morocco', label: '摩洛哥 ( Morocco Post )' },
  { value: 'mrw', label: 'MRW' },
  { value: 'multipack', label: 'Mexico Multipack' },
  { value: 'mxe56', label: '中俄速通（淼信）' },
  { value: 'nalexpress', label: '新亚物流' },
  { value: 'nedahm', label: '红马速递' },
  { value: 'nepalpost', label: '尼泊尔（Nepal Postal Services）' },
  { value: 'nigerianpost', label: '尼日利亚(Nigerian Postal)' },
  { value: 'niuzaiexpress', label: '牛仔速运' },
  { value: 'njhaobo', label: '浩博物流' },
  { value: 'nle', label: 'NLE' },
  { value: 'nmhuahe', label: '华赫物流' },
  { value: 'nntengda', label: '腾达速递' },
  { value: 'novaposhta', label: 'Nova Poshta' },
  { value: 'nuoer', label: '诺尔国际物流' },
  { value: 'nuoyaao', label: '偌亚奥国际快递' },
  { value: 'oman', label: '阿曼(Oman Post)' },
  { value: 'omniva', label: '爱沙尼亚(Eesti Post)' },
  { value: 'onway', label: '昂威物流' },
  { value: 'opek', label: 'OPEK' },
  { value: 'overseaex', label: '波音速递' },
  { value: 'paraguay', label: '巴拉圭(Correo Paraguayo)' },
  { value: 'pdstow', label: '全球速递' },
  { value: 'peex', label: '派尔快递' },
  { value: 'peixingwuliu', label: '陪行物流' },
  { value: 'peru', label: '秘鲁(SERPOST)' },
  { value: 'phlpost', label: '菲律宾（Philippine Postal）' },
  { value: 'pinsuxinda', label: '品速心达快递' },
  { value: 'pinxinkuaidi', label: '品信快递' },
  { value: 'pioneer', label: '先锋国际快递' },
  { value: 'polarisexpress', label: '北极星快运' },
  { value: 'portugalctt', label: '葡萄牙（Portugal CTT）' },
  { value: 'portugalseur', label: 'Portugal Seur' },
  { value: 'postdanmarken', label: '丹麦(Post Denmark)' },
  { value: 'postelbe', label: 'PostElbe' },
  { value: 'postenab', label: 'PostNord(Posten AB)' },
  { value: 'postennorge', label: '挪威（Posten Norge）' },
  { value: 'ptt', label: '土耳其' },
  { value: 'pzhjst', label: '急顺通' },
  { value: 'qdants', label: 'ANTS EXPRESS' },
  { value: 'qesd', label: '7E速递' },
  { value: 'qhxykd', label: '雪域快递' },
  { value: 'qhxyyg', label: '雪域易购' },
  { value: 'qskdyxgs', label: '千顺快递' },
  { value: 'quantium', label: 'Quantium' },
  { value: 'quantwl', label: '全通快运' },
  { value: 'quanxintong', label: '全信通快递' },
  { value: 'qzx56', label: '全之鑫物流' },
  { value: 'redexpress', label: 'Red Express' },
  { value: 'republic', label: '叙利亚(Syrian Post)' },
  { value: 'rhtexpress', label: '睿和泰速运' },
  { value: 'rokin', label: '荣庆物流' },
  { value: 'romanian', label: '罗马尼亚（Posta Romanian）' },
  { value: 'rrthk', label: '日日通国际' },
  { value: 'rwanda', label: '卢旺达(Rwanda i-posita)' },
  { value: 's2c', label: 'S2C' },
  { value: 'safexpress', label: 'Safexpress' },
  { value: 'samoa', label: '萨摩亚(Samoa Post)' },
  { value: 'saudipost', label: '沙特阿拉伯(Saudi Post)' },
  { value: 'scxingcheng', label: '四川星程快递' },
  { value: 'selektvracht', label: 'Selektvracht' },
  { value: 'serbia', label: '塞尔维亚(PE Post of Serbia)' },
  { value: 'seur', label: 'International Seur' },
  { value: 'sfau', label: '澳丰速递' },
  { value: 'sfpost', label: '曹操到' },
  { value: 'shanda56', label: '衫达快运' },
  { value: 'shanghaikuaitong', label: '上海快通' },
  { value: 'shanghaiwujiangmmb', label: '上海无疆for买卖宝' },
  { value: 'shangtuguoji', label: '尚途国际货运' },
  { value: 'shaoke', label: '捎客物流' },
  { value: 'shd56', label: '商海德物流' },
  { value: 'shengtongscm', label: '盛通快递' },
  { value: 'shenma', label: '神马快递' },
  { value: 'shiningexpress', label: '阳光快递' },
  { value: 'shipbyace', label: '王牌快递' },
  { value: 'shipsoho', label: '苏豪快递' },
  { value: 'shiyunkuaidi', label: '世运快递' },
  { value: 'shlexp', label: 'SHL畅灵国际物流' },
  { value: 'sihaiet', label: '四海快递' },
  { value: 'sihiexpress', label: '四海捷运' },
  { value: 'sinoex', label: '中外运速递-中文' },
  { value: 'siodemka', label: 'Siodemka' },
  { value: 'sixroad', label: '易普递' },
  { value: 'skynet', label: 'skynet' },
  { value: 'skynetworldwide', label: 'skynetworldwide' },
  { value: 'skypost', label: '荷兰Sky Post' },
  { value: 'slovak', label: '斯洛伐克(Slovenská Posta)' },
  { value: 'slpost', label: '斯里兰卡(Sri Lanka Post)' },
  { value: 'sofast56', label: '嗖一下同城快递' },
  { value: 'speeda', label: '行必达' },
  { value: 'speedoex', label: '申必达' },
  { value: 'staky', label: '首通快运' },
  { value: 'starex', label: '星速递' },
  { value: 'staryvr', label: '星运快递' },
  { value: 'subaoex', label: '速豹' },
  { value: 'sucheng', label: '速呈宅配' },
  { value: 'sudapost', label: '苏丹（Sudapost）' },
  { value: 'sufengkuaidi', label: '速风快递' },
  { value: 'superoz', label: '速配欧翼' },
  { value: 'supinexpress', label: '速品快递' },
  { value: 'szdpex', label: '深圳DPEX' },
  { value: 'taimek', label: '天美快递' },
  { value: 'tanzania', label: '坦桑尼亚(Tanzania Posts)' },
  { value: 'tcixps', label: 'TCI XPS' },
  { value: 'tdcargo', label: 'TD Cargo' },
  { value: 'thunderexpress', label: '加拿大雷霆快递' },
  { value: 'timedg', label: '万家通快递' },
  { value: 'tlky', label: '天联快运' },
  { value: 'tmg', label: '株式会社T.M.G' },
  { value: 'tntitaly', label: 'TNT Italy' },
  { value: 'tntpostcn', label: 'TNT Post' },
  { value: 'tny', label: 'TNY物流' },
  { value: 'topshey', label: '顶世国际物流' },
  { value: 'tunisia', label: '突尼斯EMS(Rapid-Poste)' },
  { value: 'uex', label: 'UEX国际物流' },
  { value: 'uganda', label: '乌干达(Posta Uganda)' },
  { value: 'ukraine', label: '乌克兰小包、大包(UkrPoshta)' },
  { value: 'ukrpost', label: '乌克兰小包、大包(UkrPost)' },
  { value: 'upsmailinno', label: 'UPS Mail Innovations' },
  { value: 'uschuaxia', label: '华夏国际速递' },
  { value: 'utaoscm', label: 'UTAO优到' },
  { value: 'vanuatu', label: '瓦努阿图(Vanuatu Post)' },
  { value: 'vietnam', label: '越南小包(Vietnam Posts)' },
  { value: 'vipexpress', label: '鹰运国际速递' },
  { value: 'wanboex', label: '万博快递' },
  { value: 'wanjiatong', label: '宁夏万家通' },
  { value: 'wdm', label: '万达美' },
  { value: 'wexpress', label: '威速递' },
  { value: 'whgjkd', label: '香港伟豪国际物流' },
  { value: 'winit', label: '万邑通' },
  { value: 'wotu', label: '渥途国际速运' },
  { value: 'wowvip', label: '沃埃家' },
  { value: 'wtdex', label: 'WTD海外通' },
  { value: 'wuyuansudi', label: '伍圆速递' },
  { value: 'wygj168', label: '万运国际快递' },
  { value: 'wzhaunyun', label: '微转运' },
  { value: 'xdshipping', label: '国晶物流' },
  { value: 'xianchengliansudi', label: '西安城联速递' },
  { value: 'xiangteng', label: '翔腾物流' },
  { value: 'xilaikd', label: '西安喜来快递' },
  { value: 'xingyuankuaidi', label: '新元快递' },
  { value: 'xinning', label: '新宁物流' },
  { value: 'xipost', label: '西邮寄' },
  { value: 'xtb', label: '鑫通宝物流' },
  { value: 'xyd666', label: '鑫远东速运' },
  { value: 'yatfai', label: '一辉物流' },
  { value: 'ycgglobal', label: 'YCG物流' },
  { value: 'yibangwuliu', label: '一邦速递' },
  { value: 'yidihui', label: '驿递汇速递' },
  { value: 'yihangmall', label: '易航物流' },
  { value: 'yilingsuyun', label: '亿领速运' },
  { value: 'yiqiguojiwuliu', label: '一柒国际物流' },
  { value: 'yishunhang', label: '亿顺航' },
  { value: 'yisong', label: '宜送' },
  { value: 'yiyou', label: '易邮速运' },
  { value: 'yjhgo', label: '武汉优进汇' },
  { value: 'ykouan', label: '洋口岸' },
  { value: 'yongbangwuliu', label: '永邦国际物流' },
  { value: 'youjia', label: '友家速递' },
  { value: 'yourscm', label: '雅澳物流' },
  { value: 'yuandun', label: '远盾物流' },
  { value: 'yujtong', label: '宇捷通' },
  { value: 'ywexpress', label: '远为快递' },
  { value: 'zenzen', label: '三三国际物流' },
  { value: 'zhitengwuliu', label: '志腾物流' },
  { value: 'zhuoshikuaiyun', label: '卓实快运' },
  { value: 'zy100', label: '中远快运' },
  { value: 'zyzoom', label: '增速跨境 ' }
]
